### ISSUE TITLE
pulumi new serverless-gcp-python or pulumi new serverless-azure-python downloads pulumi-aws

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/templates#415] opened 2022-10-20 18:07 UTC
### What happened?

When we run either of the following templates in an empty new folder:
`pulumi new serverless-gcp-python` or `pulumi new serverless-azure-python`  we download `pulumi-aws`

Code Block:
`
Collecting pulumi-aws<6.0.0,>=5.0.0
  Downloading pulumi_aws-5.18.0.tar.gz (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 36.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done`

### Steps to reproduce

1. mkdir server-gcp-python
2. pulumi new serverless-gcp-python -y ( take all the defaults)

### Expected Behavior

Only download the gcp packages for gcp and not the aws one.
Only download the azure packages for azure and not the aws one.

### Actual Behavior

Collecting pulumi-aws<6.0.0,>=5.0.0
  Downloading pulumi_aws-5.18.0.tar.gz (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 36.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done`

### Output of `pulumi about`

This is for Azure
```
❯ pulumi about
CLI
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME           VERSION
aws            5.18.0
azure-native   1.78.0
python         unknown
synced-folder  0.0.8

Host
OS       darwin
Version  11.6.8
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.10.6
'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/shaht
User           shaht
Organizations  shaht, team-ce, demo, pulumi

Dependencies:
NAME                  VERSION
pip                   22.3.0
pulumi-azure-native   1.78.0
pulumi-synced-folder  0.0.8
setuptools            65.5.0
wheel                 0.37.1
```

This is for GCP
```
❯ pulumi about
CLI
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME           VERSION
aws            5.3.0
gcp            6.36.0
go             unknown
synced-folder  0.0.8

Host
OS       darwin
Version  11.6.8
Arch     x86_64

This project is written in go: executable='/usr/local/bin/go' version='go version go1.19.1 darwin/amd64'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/shaht
User           shaht
Organizations  shaht, team-ce, demo, pulumi

Dependencies:
NAME                                        VERSION
github.com/pulumi/pulumi-gcp/sdk/v6         6.36.0
github.com/pulumi/pulumi-synced-folder/sdk  0.0.8
github.com/pulumi/pulumi/sdk/v3             3.40.2

Pulumi locates its logs in /var/folders/9q/5b8hpc2n7xxd59kb809ccgbm0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment] 2022-10-20 20:10
This is happening because the SharedFolder package supports all three providers. Two potential avenues I can think of for this:
1. Make sure there isn't a code path that can be tweaked to prevent this from happening (allowing the package to continue supporting all three providers)
2. Break it up into three packages, one per provider

**Comment by cnunciato** [comment] 2022-12-13 19:05
Closing as a dupe of #430.

**Closed by cnunciato** 2022-12-13 19:05 UTC
Labels: resolution/duplicate, kind/bug
