### ISSUE TITLE
container-aws-typescript never finishes provisioning

### ISSUE THREAD

**Issue by jkodroff** [pulumi/templates#599] opened 2023-06-15 18:44 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When running the `container-aws-typescript` template, `pulumi up` times out. This may be a transient issue, so ok to close if this cannot be reproduced, but I wanted to make sure I noted it.

<img width="1336" alt="image" src="https://github.com/pulumi/templates/assets/410614/6d0b8519-8cac-40f0-b6e7-a6bdd61c7673">

**Comment by scottslowe** [comment] 2023-06-15 19:51
Trying this now to see if I can recreate the issue.

**Comment by scottslowe** [comment] 2024-02-08 22:04
Can't reproduce (tried on both Linux and macOS systems), so I'm closing this issue.

**Closed by scottslowe** 2024-02-08 22:04 UTC
Labels: kind/enhancement, resolution/no-repro
