### ISSUE TITLE
pulumi new  serverless-azure-go has way more dependencies than the serverless-aws-go or serverless-gcp-go

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/templates#416] opened 2022-10-20 19:00 UTC
### What happened?

When you run:
`pulumi new serverless-azure-go -y` you get a bunch of dependencies that may not be needed:

### Steps to reproduce

1. mkdir my-iac-serverless-azure-go
2. cd my-iac-serverless-azure-go
3. pulumi new serverless-azure-go -y

### Expected Behavior

The azure dependencies should be relatively matching in number to the aws/gcp ones.  

### Actual Behavior

Azure has this:
```
go: downloading github.com/pulumi/pulumi-command/sdk v0.5.2
go: downloading github.com/pulumi/pulumi-synced-folder/sdk v0.0.8
go: downloading github.com/pulumi/pulumi/sdk/v3 v3.40.2
go: downloading github.com/pulumi/pulumi-azure-native/sdk v1.78.0
go: downloading google.golang.org/grpc v1.49.0
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/golang/glog v1.0.0
go: downloading golang.org/x/net v0.0.0-20221002022538-bcab6841153b
go: downloading github.com/opentracing/opentracing-go v1.2.0
go: downloading github.com/spf13/cobra v1.5.0
go: downloading github.com/rivo/uniseg v0.4.2
go: downloading github.com/uber/jaeger-client-go v2.30.0+incompatible
go: downloading golang.org/x/crypto v0.0.0-20220926161630-eccd6366d1be
go: downloading github.com/pkg/term v1.1.0
go: downloading lukechampine.com/frand v1.4.2
go: downloading golang.org/x/term v0.0.0-20220919170432-7a66f970e087
go: downloading google.golang.org/protobuf v1.28.1
go: downloading sourcegraph.com/sourcegraph/appdash v0.0.0-20211028080628-e2786a622600
go: downloading golang.org/x/sys v0.0.0-20220928140112-f11e5e49a4ec
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/inconshreveable/mousetrap v1.0.1
go: downloading github.com/uber/jaeger-lib v2.4.1+incompatible
go: downloading go.uber.org/atomic v1.10.0
go: downloading google.golang.org/genproto v0.0.0-20220930163606-c98284e70a91
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/djherbis/times v1.5.0
go: downloading github.com/go-git/go-git/v5 v5.4.2
go: downloading github.com/santhosh-tekuri/jsonschema/v5 v5.0.1
go: downloading github.com/rogpeppe/go-internal v1.9.0
go: downloading github.com/texttheater/golang-levenshtein v1.0.1
go: downloading github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/opentracing/basictracer-go v1.1.0
go: downloading gopkg.in/yaml.v3 v3.0.0
go: downloading github.com/HdrHistogram/hdrhistogram-go v1.1.2
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
go: downloading github.com/sabhiram/go-gitignore v0.0.0-20210923224102-525f6e181f06
go: downloading github.com/gofrs/uuid v4.3.0+incompatible
go: downloading github.com/stretchr/objx v0.2.0
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20220930113650-c6815a8c17ad
go: downloading github.com/go-git/go-billy/v5 v5.3.1
go: downloading github.com/imdario/mergo v0.3.13
go: downloading github.com/sergi/go-diff v1.2.0
go: downloading github.com/go-git/go-git-fixtures/v4 v4.2.1
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading github.com/emirpasic/gods v1.18.1
go: downloading github.com/acomagu/bufpipe v1.0.3
go: downloading github.com/go-git/gcfg v1.5.0
go: downloading github.com/kevinburke/ssh_config v1.2.0
go: downloading github.com/xanzy/ssh-agent v0.3.2
go: downloading github.com/cloudflare/circl v1.2.0
go: downloading github.com/matryer/is v1.2.0
go: downloading github.com/Microsoft/go-winio v0.6.0
```
While aws has the following:
```
Installing dependencies...

go: downloading github.com/pulumi/pulumi-aws-apigateway/sdk v0.0.10
go: downloading github.com/pulumi/pulumi/sdk/v3 v3.34.1
go: downloading github.com/pulumi/pulumi-aws/sdk/v5 v5.10.0
go: downloading golang.org/x/net v0.0.0-20201021035429-f5854403a974
go: downloading github.com/spf13/cobra v1.4.0
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading golang.org/x/tools v0.0.0-202101062
```
which is reasonable.

While google has the following:
```
Installing dependencies...

go: downloading github.com/pulumi/pulumi-gcp/sdk/v6 v6.36.0
go: downloading golang.org/x/net v0.0.0-20220927171203-f486391704dc
go: downloading google.golang.org/genproto v0.0.0-20220929141241-1ce7b20da813
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20220824120805-4b6e5c587895
Finished installing dependencies
```
Which seems reasonable

### Output of `pulumi about`

❯ pulumi about
CLI
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME           VERSION
aws            5.3.0
azure-native   1.78.0
command        0.5.2
go             unknown
synced-folder  0.0.8

Host
OS       darwin
Version  11.6.8
Arch     x86_64

This project is written in go: executable='/usr/local/bin/go' version='go version go1.19.1 darwin/amd64'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/shaht
User           shaht
Organizations  shaht, team-ce, demo, pulumi

Dependencies:
NAME                                        VERSION
github.com/pulumi/pulumi-azure-native/sdk   1.78.0
github.com/pulumi/pulumi-command/sdk        0.5.2
github.com/pulumi/pulumi-synced-folder/sdk  0.0.8
github.com/pulumi/pulumi/sdk/v3             3.40.2

Pulumi locates its logs in /var/folders/9q/5b8hpc2n7xxd59kb809ccgbm0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment] 2022-12-15 18:28
Hey @tusharshahrs, sorry for the delay on this one. Finally had a chance to investigate, and it looks like the majority of these are transitive deps of `pulumi-azure-native-sdk/resources`. [Here's a gist with the full tree](https://gist.github.com/cnunciato/477196721516540d7d3e4fa55e856ff7); a similar tree is produced with `azure-go`. (😬)  

I'll close this out for now, since the issue is less related to the template than to pulumi-azure-native-sdk, but thanks for submitting -- it was good to take a moment for a closer look.

**Closed by cnunciato** 2022-12-15 18:28 UTC
Labels: kind/bug, resolution/by-design
